### ISSUE TITLE
search.ml: mutate : Swap_mut => if number of allowed sources list is empty, get abort

### ISSUE THREAD

**Issue by pdreiter** [squaresLab/genprog-code#17] opened 2019-04-10 16:52 UTC
I'm seeing a response of:
 aborting: Invalid_argument("Random.int")

In debug, it's bombing  in the following code segment:

 380           | Swap_mut ->
 381             let allowed = variant#swap_sources x in
 382             let swapwith = **random allowed** in
 383               result#swap x swapwith

Here's some information from my debug trace from the random method:
**random method**
```
 161 let random atom_set =
 162   let elts = List.rev (List.rev_map fst (WeightSet.elements atom_set)) in
 163   let size = List.length elts in
 164     List.nth elts (Random.int size)
```

**Debug Trace**
```
(ocd) finish
Time: 2433803003 - pc: 1345280 - module Search
164     <|b|>List.nth elts (Random.int size)
(ocd) print size
size: int = 0
(ocd) print elts
elts: int list = []
(ocd) frame
#0 Search search.ml:164:5
164     <|b|>List.nth elts (Random.int size)
(ocd)
```

**Comment by jlacomis** [comment] 2019-04-10 17:01
Yup, this looks like duplicate of #11 which I was working on addressing in PR #15, and you can see the root cause of the bug in there. I never got to finish working on this as other things came up; at the time I was still trying to figure out a reasonable way to fix this. If you've got any good ideas, I'd welcome a PR with a patch, but I can't put much time into this myself.

I'm going to close this issue and treat #11 as the main one. Comments, suggestions, or debugging should go either there or on PR #15.

**Closed by jlacomis** 2019-04-10 17:01 UTC
